# Generated by Django 3.2 on 2021-04-10 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('value', models.CharField(blank=True, max_length=512, verbose_name='Значение')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала действия льготы')),
                ('end_date', models.DateField(auto_now_add=True, verbose_name='Дата окончания действия льготы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Льгота',
                'verbose_name_plural': 'Льготы',
            },
        ),
        migrations.CreateModel(
            name='BenefitsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Группа льгот',
                'verbose_name_plural': 'Группы льгот',
            },
        ),
        migrations.CreateModel(
            name='BenefitsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Тип Льгот',
                'verbose_name_plural': 'Типы Льгот',
            },
        ),
        migrations.CreateModel(
            name='InformationDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Загаловок')),
                ('link', models.TextField(verbose_name='Ссылка на документ')),
            ],
            options={
                'verbose_name': 'Информирующий документ',
                'verbose_name_plural': 'Информирующие документы',
            },
        ),
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Периодичность Льгот',
                'verbose_name_plural': 'Периодичности Льгот',
            },
        ),
        migrations.CreateModel(
            name='RequiredDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Загаловок')),
                ('description', models.TextField(verbose_name='Описание документа')),
            ],
            options={
                'verbose_name': 'Требуемый документ',
                'verbose_name_plural': 'Требуемые документы',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'требования',
            },
        ),
        migrations.CreateModel(
            name='RequirementsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512, verbose_name='Значение')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requirement', verbose_name='Требование')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения требований',
            },
        ),
        migrations.CreateModel(
            name='BenefitRequrements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.IntegerField(choices=[(1, 'Больше'), (2, 'Меньше'), (3, 'Равно')], default=3, verbose_name='Знак')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.benefit', verbose_name='Льгота')),
                ('requirement_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requirementsvalue', verbose_name='Необходимое значение для требования')),
            ],
            options={
                'verbose_name': 'Необходимое значение требования',
                'verbose_name_plural': 'Необходимые значения требований',
            },
        ),
        migrations.AddField(
            model_name='benefit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.benefitsgroup', verbose_name='Группа льготы'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='information_documents',
            field=models.ManyToManyField(blank=True, to='core.InformationDocuments'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='periodicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodicity', verbose_name='Периодичность льготы'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='required_documents',
            field=models.ManyToManyField(blank=True, to='core.RequiredDocuments'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.benefitstype', verbose_name='Тип льготы'),
        ),
    ]
