# Generated by Django 3.2 on 2021-04-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210410_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.benefitstype', verbose_name='Группа льготы'),
        ),
    ]
