# Generated by Django 3.2 on 2021-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210410_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='information_documents',
            field=models.ManyToManyField(blank=True, to='core.InformationDocuments'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='required_documents',
            field=models.ManyToManyField(blank=True, to='core.RequiredDocuments'),
        ),
    ]
