# Generated by Django 3.2 on 2021-04-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Льгота', 'verbose_name_plural': 'Льготы'},
        ),
        migrations.AlterField(
            model_name='benefit',
            name='information_documents',
            field=models.ManyToManyField(blank=True, null=True, to='core.InformationDocuments'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='required_documents',
            field=models.ManyToManyField(null=True, to='core.RequiredDocuments'),
        ),
    ]
